services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: connectcv-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./frontend/public/portfolios:/app/portfolios
      - d:/TL_CN/K_7/EXE_101/mau_CV:/mau_CV:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: connectcv-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
