const {test}=require('node:test');const assert=require('node:assert/strict');
const {groundCv,buildPlanningProfile}=require('../src/services/cvGroundingService');
const {buildCvTemplateHtml}=require('../src/services/templateHtmlBuilder');
const {getAvailableTemplates}=require('../src/services/templateService');
const {buildAtsDocx}=require('../src/services/atsExportService');
const AdmZip=require('adm-zip');
const profile={fullName:'Real Candidate',email:'real@example.com',skills:['Excel','C++'],summary:'Handled payments.',experience:[{company:'Real Shop',role:'Cashier',time:'2023 - 2024',bullets:['Handled 20 payments daily.']},{company:'Other Shop',role:'Assistant',time:'2022',bullets:['Recorded payments in Excel.']}],education:[{school:'Real College',degree:'Accounting',time:'2020 - 2022',highlight:''}]};
const malicious={fullName:'Fake Name',summary:'Led 50 engineers and increased revenue by 80%.',targetRole:'CTO',highlightedSkills:{technical:['AWS']},education:[{school:'Fake University',degree:'PhD',duration:'2010',highlights:'4.0'}],tailoredExperience:[{organization:'Fake Employer',achievements:['80%']}],atsScore:99};
test('AI cannot add facts, numbers, skills, degrees or identities in either language',()=>{for(const language of ['vi','en']){const d=groundCv(profile,malicious,language,{targetRole:'Cashier',jdText:'Need Excel and C++'});assert.equal(d.fullName,profile.fullName);assert.equal(d.summary,profile.summary);assert.deepEqual(d.highlightedSkills.technical,profile.skills);assert.equal(d.education[0].highlights,'');assert.equal(d.education[0].school,'Real College');assert.equal(d.tailoredExperience.length,2);assert.deepEqual(d.tailoredExperience[0].achievements,profile.experience[0].bullets);assert.equal(d.atsScore,100);}});
test('Source IDs allow ordering but duplicate/unknown IDs cannot add or lose history',()=>{const d=groundCv(profile,{experienceOrder:['experience:1','experience:1','experience:999']});assert.deepEqual(d.tailoredExperience.map(e=>e.organization),['Other Shop','Real Shop']);const round=groundCv(profile,d);assert.deepEqual(round.tailoredExperience.map(e=>e.organization),['Other Shop','Real Shop']);});
test('No hardcoded biographical defaults in all 74 layouts and both languages',()=>{const all=getAvailableTemplates('vi');assert.equal(all.length,74);for(const lang of ['vi','en'])for(const t of all){const h=buildCvTemplateHtml(t,malicious,{fullName:'Beginner'},lang);const visibleText=h.replace(/<style[\s\S]*?<\/style>|<script[\s\S]*?<\/script>/gi,'').replace(/<[^>]+>/g,' ');for(const bad of ['Fake Employer','Fake University','Led 50','3.6/4.0','25%','kienminh.dev@gmail.com','24/08/1998','1M+'])assert.ok(!visibleText.includes(bad),`${t.slug} ${bad}`);assert.ok(h.includes(`data-template="${t.id}"`));}});
test('74 layouts retain only supplied facts including accounting and empty GPA',()=>{for(const lang of ['vi','en'])for(const t of getAvailableTemplates(lang)){const h=buildCvTemplateHtml(t,malicious,profile,lang).replace(/<style[\s\S]*?<\/style>|<script[\s\S]*?<\/script>/gi,'');assert.ok(h.includes('Real Shop'));assert.ok(h.includes('Real College'));assert.ok(h.includes('Handled 20 payments daily.'));assert.ok(!h.includes('AWS'));assert.ok(!h.includes('4.0'));}});
test('Long profile remains complete or fails explicitly before AI',()=>{assert.ok(buildPlanningProfile({summary:'x'.repeat(13000),experience:profile.experience}).includes('Real Shop'));assert.throws(()=>buildPlanningProfile({summary:'x'.repeat(60001)}),e=>e.statusCode===400);});
test('Empty profile has no fake score, education, experience or skills',()=>{const d=groundCv({},malicious);assert.equal(d.atsScore,0);assert.equal(d.education.length,0);assert.equal(d.tailoredExperience.length,0);assert.deepEqual(d.highlightedSkills.technical,[]);assert.equal(d.targetRole,'');});
test('ATS Word keeps source text in normal paragraphs, no textbox or graphics',()=>{const buf=buildAtsDocx(malicious,profile,'en');const z=new AdmZip(buf);const xml=z.readAsText('word/document.xml');for(const bad of ['txbxContent','w:pict','Fake Employer','Fake University','80%'])assert.ok(!xml.includes(bad));assert.ok(xml.includes('<w:p>'));assert.ok(xml.includes('Handled 20 payments daily.'));assert.ok(xml.indexOf('Real Candidate')<xml.indexOf('Real Shop'));assert.ok(xml.indexOf('Real Shop')<xml.indexOf('Real College'));});

test('Keyword matching distinguishes Excel from Excellent and handles C++',()=>{const d=groundCv({skills:['Excel','C++']},{},'en',{jdText:'Excellent communication and C++'});assert.deepEqual(d.matchedKeywords,['C++']);assert.equal(d.atsScore,50);});
test('Missing degrees, highlights and timelines stay empty after language switch',()=>{const p={fullName:'Ứng viên',education:[{school:'Trường thật',degree:'',time:'',highlight:''}],experience:[{company:'Công ty thật',role:'',time:'',bullets:[]}]};const en=groundCv(p,malicious,'en');const vi=groundCv(en.sourceProfile,en,'vi');assert.equal(vi.education[0].degree,'');assert.equal(vi.education[0].highlights,'');assert.equal(vi.tailoredExperience[0].duration,'');});

test('Translation does not invent bachelor equivalence or honors awards',()=>{const d=groundCv({education:[{school:'Đại học FPT Cần Thơ',degree:'Kỹ sư Kỹ thuật Phần mềm',highlight:'Tốt nghiệp loại Giỏi - GPA 3.6/4.0'}]},{},'en');assert.equal(d.education[0].degree,'Engineer in Software Engineering');assert.equal(d.education[0].highlights,'Graduated: Good classification - GPA 3.6/4.0');});
