const assert=require('node:assert/strict'),fs=require('fs');const root=process.env.TEST_ROOT || require('node:path').resolve(__dirname,'..');
const output=fs.mkdtempSync(require('node:path').join(require('node:os').tmpdir(),'connectcv-english-'));
let mode='good',calls=0;
const gp=require.resolve(root+'/src/services/geminiService');require.cache[gp]={id:gp,filename:gp,loaded:true,exports:{callGeminiJSON:async prompt=>{calls++;if(prompt.startsWith('Translate these')){const rows=JSON.parse(prompt.split('FIELDS:\n')[1]);return {translations:rows.map(e=>({id:e.id,text:mode==='bad'?'Invented 999%':({'summary':'A motivated software engineer with experience in backend development, database design and application performance optimization. Seeking to contribute to large-scale technology solutions as a Senior Backend Engineer.','experience:0.bullet:0':'Developed the ConnectCV AI platform, serving 500+ users.','experience:0.bullet:1':'Built RESTful APIs with Node.js and Express, reducing response time by 25%.','experience:0.bullet:2':'Used PostgreSQL and Docker to standardize deployment and improve data security.'}[e.id] || 'English translation')+(mode==='semantic'?' Led a global team.':'')}))};}if(prompt.startsWith('Independently')){const pairs=JSON.parse(prompt.split('PAIRS:\n')[1]);return {checks:pairs.map(p=>({id:p.id,faithful:mode!=='semantic',english:true}))};}return {experienceOrder:['experience:0'],skillOrder:['skill:0']};},keyManager:{isRateLimitError:()=>false}}};
const {groundCv}=require(root+'/src/services/cvGroundingService'),{translateCv}=require(root+'/src/services/cvTranslationService'),ts=require(root+'/src/services/templateService');
const profile={fullName:'Huỳnh Kiến Minh',targetRole:'Lập trình viên Backend',phone:'(+84) 912 345 678',email:'kienminh.dev@gmail.com',address:'Cần Thơ, Việt Nam',avatarUrl:'/images/avatars/default_v2.jpg',summary:'Kỹ sư phần mềm giàu nhiệt huyết với nền tảng vững chắc về phát triển hệ thống Backend, thiết kế cơ sở dữ liệu và tối ưu hóa hiệu năng ứng dụng. Mục tiêu trở thành Senior Backend Engineer đóng góp vào các giải pháp công nghệ quy mô lớn.',skills:['Node.js','Docker'],experience:[{company:'ConnectCV (Nền tảng AI Career)',role:'Lập trình viên Backend',time:'06/2023 - Hiện tại',bullets:['Phát triển nền tảng AI ConnectCV phục vụ 500+ người dùng.','Thiết kế RESTful API bằng Node.js và Express, giảm 25% thời gian phản hồi.','Ứng dụng PostgreSQL và Docker để chuẩn hóa triển khai và bảo mật dữ liệu.']}],education:[{school:'Đại học FPT Cần Thơ',degree:'Kỹ sư Kỹ thuật Phần mềm',time:'2019 - 2023',highlight:'Tốt nghiệp loại Giỏi - GPA 3.6/4.0'}]};
(async()=>{
 const original=groundCv(profile,{},'en');const cv=await translateCv(original);assert.ok(cv.grounding.translationVerified);assert.ok(!/[àáạảãăằắặẳẵâầấậẩẫèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]/i.test(cv.summary+cv.tailoredExperience[0].achievements.join('')));assert.ok(cv.tailoredExperience[0].achievements[0].includes('500+'));assert.ok(cv.tailoredExperience[0].achievements[1].includes('25%'));
 const rerender=groundCv(profile,cv,'en',cv.sourceContext);assert.equal(rerender.summary,cv.summary);assert.deepEqual(rerender.tailoredExperience,cv.tailoredExperience);const forged=structuredClone(cv);forged.translationBundle.values.summary='Fabricated 999%';assert.notEqual(groundCv(profile,forged,'en',cv.sourceContext).summary,'Fabricated 999%');
 for(const t of ts.getAvailableTemplates('en')){const h=ts.renderCVDataToTemplateHtml(t,cv,profile,'en');assert.ok(h.includes(cv.tailoredExperience[0].achievements[0]),t.id);assert.ok(!h.includes('giàu nhiệt huyết'));}
 const express=require(root+'/node_modules/express'),app=express();app.use(express.json());app.use('/api/cv',require(root+'/src/routes/cv'));const server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s))});
 try{const post=async(path,body)=>{const r=await fetch(`http://127.0.0.1:${server.address().port}/api/cv`+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return {status:r.status,data:await r.json()}};
 const response=await post('/generate',{profile,language:'en',templateMode:'manual',selectedTemplateId:'formal',jdText:'Seeking a backend developer skilled in Node.js.'});assert.equal(response.status,200,JSON.stringify(response.data));assert.equal(response.data.data.summary,cv.summary);assert.ok(response.data.renderedHtml.includes('data-native-topcv="formal"'));
 const render=await post('/render',{profile,cvData:response.data.data,language:'en',templateId:'formal'});assert.equal(render.status,200);assert.ok(render.data.renderedHtml.includes(cv.summary));fs.writeFileSync(output+'/formal-verified.html',render.data.renderedHtml);fs.writeFileSync(output+'/formal-verified.json',JSON.stringify({profile,cv:response.data.data}));
 mode='semantic';const semantic=await post('/generate',{profile,language:'en',targetRole:'Other Backend Role',templateMode:'manual',selectedTemplateId:'formal',jdText:'Seeking a backend developer skilled in Node.js.'});assert.equal(semantic.status,422);mode='bad';const badProfile={...profile,summary:'Tôi cải thiện hiệu năng 77%.'};const bad=await post('/generate',{profile:badProfile,language:'en',templateMode:'manual',selectedTemplateId:'formal',jdText:'Seeking a backend developer skilled in Node.js.'});assert.equal(bad.status,422);assert.ok(!bad.data.renderedHtml);
 console.log('PASS: complete English, preserved source numbers, signed translations survive all 74 renderers, forged translations rejected, real generate/render routes and invalid translation fails explicitly');
 }finally{server.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
