const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');const root=process.env.TEST_ROOT||path.resolve(__dirname,'..');const ts=require(root+'/src/services/templateService'),{getBrowser,generateCvPdf}=require(root+'/src/services/pdfService'),{prepareCvPage}=require(root+'/src/services/cvRenderRuntime'),{getDesign}=require(root+'/src/services/designRegistry');
const output=process.env.CV_DESIGN_OUTPUT_DIR||path.join(require('os').tmpdir(),'connectcv-design-qa');fs.mkdirSync(output,{recursive:true});
(async()=>{const browser=await getBrowser(),page=await browser.newPage(),results=[];try{
 for(const language of ['vi','en']){fs.mkdirSync(output+'/'+language,{recursive:true});for(const t of ts.getAvailableTemplates(language)){
  const html=ts.getTemplatePreviewHtml(t.id,language);await prepareCvPage(page,html,{scale:1});
  const inspect=()=>page.evaluate(()=>{const root=document.querySelector('.cv-page-container'),origin=root.getBoundingClientRect();return [...root.querySelectorAll('h1,h2,p,img,.cat-sidebar,.cat-main,.formal-hero,.formal-job')].map(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {text:e.textContent,x:r.x-origin.x,y:r.y-origin.y,w:r.width,h:r.height,color:s.color,bg:s.backgroundColor,font:s.fontFamily,size:s.fontSize}})});
  const print=await inspect();await page.emulateMediaType('screen');const screen=await inspect();assert.deepEqual(screen,print,t.id+' screen/print drift');
  assert.ok(print.some(e=>e.text.includes(language==='en'?'Nguyen Minh An':'Nguyễn Minh An')),t.id+' no demo name');
  await page.emulateMediaType('print');const el=await page.$('.cv-page-container');await el.screenshot({path:output+'/'+language+'/'+t.id+'.png'});
  const design=getDesign(t.slug,language);assert.equal(html.includes('data-design-version="'+ts.PREVIEW_VERSION+'"'),true);
  results.push({slug:t.id,language,font:design.style.font,accent:design.style.a,screenPrintExact:true,referenceStatus:design.referenceStatus});
 }
 console.log('Verified '+language+': 74 packaged-font previews, no screen/print geometry or color drift.');}
 const profile={fullName:'TEST CANDIDATE',targetRole:'Backend Developer',summary:'Builds reliable software and APIs using Node.js and PostgreSQL.',phone:'0123456789',email:'example@example.com',avatarUrl:'/images/avatars/default_v2.jpg',skills:['Node.js','PostgreSQL'],experience:[{company:'Synthetic Example Company',role:'Backend Developer',time:'2020 - 2026',bullets:['Built APIs serving 700+ test accounts.','Reduced response time by 17%.']}],education:[{school:'Synthetic Example University',degree:'Software Engineering',time:'2016 - 2020',highlight:'GPA 3.2/4.0'}]};const {groundCv}=require(root+'/src/services/cvGroundingService');const cv=groundCv(profile,{},'en');
 for(const slug of ['ambitious','formal','tiktop']){const html=ts.renderCVDataToTemplateHtml(ts.getTemplateById(slug,'en'),cv,profile,'en');fs.writeFileSync(output+'/'+slug+'.html',html);fs.writeFileSync(output+'/'+slug+'.pdf',await generateCvPdf({html}));const {generateLayoutDocx}=require(root+'/src/services/docxLayoutService');fs.writeFileSync(output+'/'+slug+'.docx',await generateLayoutDocx({html}));console.log('PDF + embedded-font Word: '+slug);}
 const longProfile={...profile,experience:Array.from({length:15},(_,i)=>({...profile.experience[0],company:'Synthetic Company '+i,bullets:['Long content item '+i+' repeated to check pagination and preservation of every source achievement.','FINAL_SOURCE_ITEM_'+i]}))};const longCv=groundCv(longProfile,{},'en');const html=ts.renderCVDataToTemplateHtml(ts.getTemplateById('ambitious','en'),longCv,longProfile,'en');fs.writeFileSync(output+'/long.pdf',await generateCvPdf({html}));
 fs.writeFileSync(output+'/results.json',JSON.stringify({version:ts.PREVIEW_VERSION,results},null,2));console.log('PASS: 148 preview variants, exact screen/print geometry/colors, packaged fonts, representative Word/PDF and long CV.');
 }finally{await page.close();await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
