const assert=require('node:assert/strict'),fs=require('fs');
const root=process.env.TEST_ROOT || require('node:path').resolve(__dirname,'..');
const output=fs.mkdtempSync(require('node:path').join(require('node:os').tmpdir(),'connectcv-grounding-'));
let captured='',calls=0;
const gp=require.resolve(root+'/src/services/geminiService');require.cache[gp]={id:gp,filename:gp,loaded:true,exports:{callGeminiJSON:async p=>{captured=p;calls++;return {summary:'INVENTED 80%',atsScore:99,highlightedSkills:{technical:['AWS']},education:[{school:'Fake University',highlights:'4.0'}],tailoredExperience:[{organization:'Fake Employer',achievements:['INVENTED 80%']},{organization:'Extra Employer'}],experienceOrder:['experience:1','experience:0','experience:1','invalid'],skillOrder:['skill:0','skill:999']};},keyManager:{isRateLimitError:()=>false}}};
const express=require(require.resolve('express',{paths:[root]})),app=express();app.use(express.json({limit:'2mb'}));app.use('/api/cv',require(root+'/src/routes/cv'));
const profile={fullName:'Audit Candidate',phone:'0900000000',email:'audit@example.com',skills:['Excel'],summary:'Handled payments.',education:[{school:'Real College',degree:'Accounting',time:'2020 - 2022',highlight:''}],experience:[{company:'Real Shop',role:'Cashier',time:'2023 - 2024',bullets:['Handled 20 payments daily.']},{company:'Other Shop',role:'Assistant',time:'2022',bullets:['Recorded payments.']}]};
(async()=>{const server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s))});const base=`http://127.0.0.1:${server.address().port}/api/cv`;const post=async(path,body)=>{const r=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return {r,b:await r.json()}};
try{
 let count=0,last;
 for(const language of ['vi','en'])for(const templateMode of ['auto','manual'])for(const t of require(root+'/src/services/templateService').getAvailableTemplates(language)){
 const {r,b}=await post('/generate',{profile,language,templateMode,selectedTemplateId:t.id,jdText:'Seeking a cashier with Excel to handle payments.',targetRole:'Cashier'});assert.equal(r.status,200,JSON.stringify(b));assert.equal(b.appliedTemplate.id,t.id);assert.equal(b.data.summary,profile.summary);assert.equal(b.data.education[0].highlights,'');assert.deepEqual(b.data.highlightedSkills.technical,['Excel']);assert.deepEqual(b.data.tailoredExperience.map(e=>e.organization),['Other Shop','Real Shop']);assert.ok(!b.renderedHtml.includes('INVENTED'));assert.ok(!b.renderedHtml.includes('Fake University'));count++;last=b.data;
 }
 let x=await post('/generate',{profile:{fullName:'Beginner'},language:'en',templateMode:'manual',selectedTemplateId:'classic_1',jdText:'Seeking a cashier with Excel to handle payments.'});assert.equal(x.r.status,200);assert.equal(x.b.data.tailoredExperience.length,0);assert.equal(x.b.data.education.length,0);assert.equal(x.b.data.atsScore,0);
 x=await post('/generate',{profile:{summary:'X'.repeat(13000),experience:profile.experience},templateMode:'manual',selectedTemplateId:'classic_1',jdText:'Seeking a cashier with Excel to handle payments.'});assert.equal(x.r.status,200);assert.ok(captured.includes('Real Shop'));
 const before=calls;let invalid=await post('/generate',{profile:'invalid JSON',templateMode:'manual',selectedTemplateId:'classic_1',jdText:'Seeking a cashier with Excel to handle payments.'});assert.equal(invalid.r.status,400);assert.equal(calls,before);x=await post('/generate',{profile:{summary:'X'.repeat(60001)},templateMode:'manual',selectedTemplateId:'classic_1',jdText:'Seeking a cashier with Excel to handle payments.'});assert.equal(x.r.status,400);assert.equal(calls,before);
 x=await post('/translate',{cvData:last,targetLanguage:'vi'});assert.equal(x.r.status,200);assert.equal(x.b.data.education[0].highlights,'');assert.deepEqual(x.b.data.tailoredExperience.map(e=>e.organization),['Other Shop','Real Shop']);assert.equal(calls,before);
 x=await post('/translate',{cvData:{summary:'Old unverified'},targetLanguage:'en'});assert.equal(x.r.status,400);
 x=await post('/ats-score',{cvText:'Candidate has Excel skills and handles payments accurately.',jdText:'Seeking cashier with Excel and payments experience.'});assert.equal(x.r.status,200);assert.equal(x.b.data.scoreType,'text_token_overlap');assert.ok(!x.b.data.actionableRecommendations.join().includes('Bổ sung Docker'));
 for(const format of ['ats','design']){
 const r=await fetch(base+'/export-docx',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({format,cvData:last,userProfile:profile,templateId:'classic_1',language:'en'})});assert.equal(r.status,200);fs.writeFileSync(output+'/'+format+'.docx',Buffer.from(await r.arrayBuffer()));
 }
 const r=await fetch(base+'/export-pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({format:'ats',cvData:last,userProfile:profile,templateId:'classic_1',language:'en'})});assert.equal(r.status,200);fs.writeFileSync(output+'/ats.pdf',Buffer.from(await r.arrayBuffer()));
 fs.writeFileSync(output+'/result.json',JSON.stringify({generationCases:count,emptyProfile:'passed',longProfile:'passed',oversizeRejectedBeforeAI:'passed',translation:'passed',atsExport:'passed'},null,2));console.log('Evidence:',output);console.log('PASS:',count,'generation cases + empty/long/oversize/translation/scoring/ATS and design exports');
}finally{server.close();const mod=require.cache[require.resolve(root+'/src/services/pdfService')];if(mod?.exports?.getBrowser)(await mod.exports.getBrowser()).close()}})().catch(e=>{console.error(e);process.exitCode=1});
