'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),http=require('http');
const ROOT='/app';let passed=[];
const admissionDir=fs.mkdtempSync(path.join(os.tmpdir(),'feature-admission-'));process.env.FEATURE_STATE_DIR=admissionDir;
const check=(name,fn)=>Promise.resolve().then(fn).then(()=>{passed.push(name);console.log('PASS '+name)});
(async()=>{
 const {featureSecurity}=require(ROOT+'/src/middlewares/featureSecurity');
 const invoke=async(req)=>{let code=0,next=false;const res={setHeader(){},status(n){code=n;return this},json(){return this},once(){}};await featureSecurity({method:'POST',body:{},path:'/message',socket:{remoteAddress:'127.0.0.1'},...req},res,()=>{next=true});return {code,next};};
 await check('feature admission requires server identity',async()=>{assert.equal((await invoke({body:{userId:'forged'},headers:{'x-user-id':'forged'}})).code,401);});
 await check('history type and aggregate size rejected',async()=>{assert.equal((await invoke({user:{id:'h'},body:{history:{}}})).code,400);assert.equal((await invoke({user:{id:'h'},body:{history:[{message:'x'.repeat(33000)}]}})).code,400)});
 await check('forwarded-for cannot reset account quota',async()=>{for(let i=0;i<15;i++)assert((await invoke({user:{id:'quota'},headers:{'x-forwarded-for':'fake-'+i}})).next);assert.equal((await invoke({user:{id:'quota'},headers:{'x-forwarded-for':'new-fake'}})).code,429)});
 const {redact,planningProfile}=require(ROOT+'/src/services/aiProfilePrivacy');
 await check('AI planning redacts structured identity and credentials',()=>{const x=planningProfile({fullName:'private-name',email:'private@test',phone:'123',avatarUrl:'photo',skills:['Node.js'],experience:[{company:'FACT',role:'Engineer',bullets:['FACT']}],secret:'private-secret'});assert(!x.includes('private'));assert(x.includes('FACT'));assert(x.includes('Node.js'));assert.equal(planningProfile('unstructured PII'), '')});
 const {FeatureBudget}=require(ROOT+'/src/services/featureBudget');
 const budgetDir=fs.mkdtempSync(path.join(os.tmpdir(),'budget-check-')),budgetFile=path.join(budgetDir,'quota.json');
 await check('daily budget survives restart and serializes concurrent spending',async()=>{const budget=new FeatureBudget(budgetFile,2);const results=await Promise.allSettled(Array.from({length:10},()=>budget.consume('daily-user')));assert.equal(results.filter(r=>r.status==='fulfilled').length,2);await assert.rejects(new FeatureBudget(budgetFile,2).consume('daily-user'),e=>e.status===429)});
 fs.rmSync(budgetDir,{recursive:true});
 await check('render concurrency stays occupied until work completes',async()=>{const {withRenderSlot}=require(ROOT+'/src/services/renderCapacity');let a,b;const one=withRenderSlot(()=>new Promise(r=>a=r)),two=withRenderSlot(()=>new Promise(r=>b=r));await assert.rejects(withRenderSlot(async()=>{}),e=>e.status===503);a();await one;await withRenderSlot(async()=>{});b();await two;});
 await check('production budget fails closed without durable storage declaration',async()=>{const old=process.env.NODE_ENV;process.env.NODE_ENV='production';try{assert.throws(()=>require(ROOT+'/src/services/featureBudget').consumeFeatureBudget('production-user'),e=>e.status===503);}finally{if(old===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=old;}});
 await check('API keys and bearer tokens are removed from service errors',()=>{const {safeError}=require(ROOT+'/src/services/securityError');const fake='AIza'+'x'.repeat(35);const error=safeError(new Error('URL ?key='+fake+' Bearer fake.secret.token'));assert(!error.includes(fake));assert(!error.includes('fake.secret.token'));assert(error.includes('REDACTED'));});
 const {CommunityStore,publicEntry}=require(ROOT+'/src/services/communityStore');
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'community-security-')),file=path.join(dir,'store.json');const store=new CommunityStore(file),user={id:'fixture-user'},entry={companyName:'TEST',interviewQuestions:['TEST QUESTION'],sharedAt:new Date().toISOString()};
 await check('concurrent duplicate submits persist one reward only',async()=>{const results=await Promise.allSettled(Array.from({length:10},()=>store.submit(user,entry,'testhash')));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(store.state.ledger.length,1);assert.equal(store.state.ledger[0].amount,5);assert.equal(results.find(r=>r.status==='fulfilled').value.awardedCredits,0)});
 const restarted=new CommunityStore(file);
 await check('cooldown survives restart and altered content',async()=>{await assert.rejects(restarted.submit(user,entry,'changedhash'),e=>e.status===429);assert.equal(restarted.state.ledger.length,1)});
 await check('public post DTO excludes private metadata',()=>{const e=publicEntry({...restarted.entries[0],likedIps:['IP'],likedUsers:['ID'],ownerId:'ID',awardedCredits:5});assert(!JSON.stringify(e).includes('IP'));for(const k of ['likedUsers','ownerId','likedIps','contentHash','awardedCredits'])assert(!(k in e))});
 await check('likes belong to authenticated user and persist',async()=>{const id=restarted.entries[0].id;assert.equal((await restarted.like({id:'like-user'},id)).likesCount,1);assert.equal((await restarted.like({id:'like-user'},id)).likesCount,0);assert.equal(new CommunityStore(file).entries[0].likesCount,0)});
 fs.rmSync(dir,{recursive:true});
 await check('all live write routes fail closed without login',async()=>{for(const route of ['/api/cv/export-pdf','/api/cv/render','/api/cv/generate','/api/interview/start','/api/interview/live-summary','/api/interview/debrief','/api/interview/community-questions/test/like','/api/chatbot/message']){const r=await fetch('http://127.0.0.1:5000'+route,{method:'POST',headers:{'Content-Type':'application/json','x-forwarded-for':'spoof'},body:JSON.stringify({html:'<html></html>',userId:'forged'})});assert.equal(r.status,401,route)}});
 let hits=0;const server=http.createServer((req,res)=>{hits++;res.end('external');});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const fixturePort=server.address().port;
 const {getBrowser,generateCvPdf}=require(ROOT+'/src/services/pdfService');const {prepareCvPage}=require(ROOT+'/src/services/cvRenderRuntime');const b=await getBrowser(),p=await b.newPage();
 try{
 await check('saved photo crop is restored without running document scripts',async()=>{await prepareCvPage(p,'<html><head></head><body><div class="cv-page-container"><img style="width:100px;height:100px" data-photo-zoom="2" data-photo-x="20" data-photo-y="-10" src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="></div></body></html>');const crop=await p.evaluate(()=>({transform:document.querySelector('img').style.transform,frame:!!document.querySelector('.cv-photo-frame')}));assert(crop.frame);assert(crop.transform.includes('scale(2)'));assert(crop.transform.includes('20%'));});
 await check('export blocks scripts, handlers, frames, CSS SSRF and remote images',async()=>{const html=`<html><head><style>@import url('http://127.0.0.1:${fixturePort}/css');body{background:url('http://127.0.0.1:${fixturePort}/bg')}</style></head><body><div class="cv-page-container">SAFE_TEXT<img src="http://127.0.0.1:${fixturePort}/image" onerror="document.body.innerHTML='EXECUTED'"><iframe src="http://127.0.0.1:${fixturePort}/frame"></iframe><a href="javascript:alert(1)">TEXT</a></div><script>document.body.innerHTML='EXECUTED';fetch('http://127.0.0.1:${fixturePort}/script')</script></body></html>`;await prepareCvPage(p,html);assert.equal(hits,0);const state=await p.evaluate(()=>({text:document.body.innerText,unsafe:document.querySelectorAll('script,iframe,[onerror],a[href]').length}));assert(state.text.includes('SAFE_TEXT'));assert(!state.text.includes('EXECUTED'));assert.equal(state.unsafe,0);const pdf=await generateCvPdf({html});assert(pdf.length>1000);assert.equal(hits,0)});
 }finally{await p.close();await b.close();server.close();}
 fs.writeFileSync('/tmp/feature-security-results.json',JSON.stringify({passed,authSourceChanged:false,centralCreditsIntegrated:false},null,2));fs.rmSync(admissionDir,{recursive:true});console.log('PASS '+passed.length+' security checks');
})().catch(e=>{console.error(e);process.exitCode=1});
